### PR TITLE
bump php version to 8.1 and psr to 3.0.0 package

### PR DESCRIPTION
**Pull request by abdelmoniemMohamed**

### CODE REVIEW

**Comment by sebastianpisula** [comment]
any updates?

**Comment by seostudio** [comment]
bump

**Comment by powli** [comment]
Hey @seostudio and @sebastianpisula. We are currently in the process of transitioning the package to compatibility with the newer `psr/log` versions. At the same time we will be dropping PHP 7 support and upgrading the package code to the newer PHP features.

**Comment by Sebastian80** [comment]
Hi, we released a new version that provides PHP 8.1 and PSR 3.0 support.
Please see → [new release](https://github.com/netresearch/dhl-sdk-api-unified-location-finder/releases/tag/3.1.0)

**Pull request closed without merging**
